Fix missing return values
* return false for error conditions
* fixes return-mismatch issues which are fatal by default with gcc-14

src/telephonyservice_call.c:46:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_call.c:96:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_call.c:142:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_call.c:188:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:129:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:135:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:186:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:192:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:213:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:219:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:244:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:295:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:346:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:398:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:457:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:557:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
src/telephonyservice_sim.c:563:17: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>